# Generated by Django 4.0.3 on 2022-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='comments',
        ),
        migrations.AddField(
            model_name='answers',
            name='comments',
            field=models.ManyToManyField(related_name='commentsForAnswer', to='api.comments'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(to='api.answers'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='comments',
        ),
        migrations.AddField(
            model_name='questions',
            name='comments',
            field=models.ManyToManyField(related_name='commentsForQuestions', to='api.comments'),
        ),
    ]
