# Generated by Django 4.0.3 on 2022-07-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answers_comments_alter_questions_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
